title=oefalgoarithm.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=U3
subject=algo
notion=algoarithm
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U3/algo/oefalgoarithm.fr
