title=rotshoot.cn
type=wims
extends=plbank:/demo/wims/template.pl
level=H3
subject=geometry
notion=rotshoot
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H3/geometry/rotshoot.cn
