title=breuken-3.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H2
subject=arithmetic
notion=breuken-3
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H2/arithmetic/breuken-3.nl
