title=oppervlak-1.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H1
subject=number
notion=oppervlak-1
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H1/number/oppervlak-1.nl
