title=verhoudingen-2.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H1
subject=number
notion=verhoudingen-2
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H1/number/verhoudingen-2.nl
