# Generated by Django 2.0.4 on 2018-11-26 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('consumer', models.CharField(blank=True, choices=[('moodle', 'moodle')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('open', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classmanagement.Course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playexo.Activity')),
                ('pltp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PLTP')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', jsonfield.fields.JSONField(default='{}')),
                ('seed', models.CharField(default=time.time, max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.IntegerField(null=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playexo.Activity')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playexo.Activity')),
                ('current_pl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.PL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built', models.BooleanField(default=False)),
                ('envid', models.CharField(max_length=300, null=True)),
                ('context', jsonfield.fields.JSONField(null=True)),
                ('activity_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playexo.SessionActivity')),
                ('pl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.PL')),
            ],
        ),
        migrations.CreateModel(
            name='SessionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('built', models.BooleanField(default=False)),
                ('envid', models.CharField(max_length=300, null=True)),
                ('context', jsonfield.fields.JSONField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='sessionexercise',
            unique_together={('pl', 'activity_session')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionactivity',
            unique_together={('user', 'activity')},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('consumer', 'consumer_id')},
        ),
    ]
