# Generated by Django 2.1.4 on 2019-01-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
        ('playexo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionexercise',
            old_name='activity_session',
            new_name='session_activity',
        ),
        migrations.AlterUniqueTogether(
            name='sessionexercise',
            unique_together={('pl', 'session_activity')},
        ),
    ]
