title=graphadd.en
type=wims
extends=plbank:/demo/wims/template.pl
level=H5
subject=analysis
notion=graphadd
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H5/analysis/graphadd.en
