title=OEFtriang5.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H1
subject=geometry
notion=OEFtriang5
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H1/geometry/OEFtriang5.fr
