title=oefcalcul.es
type=wims
extends=plbank:/demo/wims/template.pl
level=H2
subject=algebra
notion=calcul
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H2/algebra/oefcalcul.es
