title=oefC2iB4Word.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=U1
subject=infonet
notion=C2iB4Word
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U1/infonet/oefC2iB4Word.fr
