# Generated by Django 2.0.7 on 2018-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaanswer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
