# Generated by Django 2.0.7 on 2018-08-05 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaquestion',
            name='hit',
        ),
    ]
