# Generated by Django 2.0.7 on 2018-07-31 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_qaanswer_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qaanswer',
            name='accepted',
        ),
    ]
