# Generated by Django 2.0.7 on 2018-08-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_remove_qaquestion_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaquestion',
            name='popularity',
            field=models.FloatField(default=0),
        ),
    ]
