# Generated by Django 2.0.4 on 2018-05-03 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import user_profile.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playexo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('consumer_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('editor_theme', enumfields.fields.EnumIntegerField(default=21, enum=user_profile.enums.EditorTheme)),
                ('role', enumfields.fields.EnumIntegerField(default=4, enum=user_profile.enums.Role)),
                ('color_blindness', enumfields.fields.EnumIntegerField(default=0, enum=user_profile.enums.ColorBlindness)),
                ('activity', models.ManyToManyField(blank=True, to='playexo.Activity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
