# Generated by Django 2.0.6 on 2018-07-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
    ]
