# Generated by Django 2.1 on 2018-09-06 09:22

from django.db import migrations
import enumfields.fields
import user_profile.enums


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20180816_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='editor_theme',
            field=enumfields.fields.EnumIntegerField(default=9, enum=user_profile.enums.EditorTheme),
        ),
    ]
