title=OEFondes.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H6
subject=physics
notion=OEFondes
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H6/physics/OEFondes.fr
