title=deductio.com
type=wims
extends=plbank:/demo/wims/template.pl
level=template
subject=deductio.com
notion=
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=template/deductio.com/
