title=doc.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=template
subject=doc.nl
notion=
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=template/doc.nl/
