title=calcff.it
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=algebra
notion=calcff
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/algebra/calcff.it
