title=permgroup.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=algebra
notion=permgroup
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/algebra/permgroup.fr
