title=smallgroup.cn
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=algebra
notion=smallgroup
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/algebra/smallgroup.cn
