title=SelectSet
text=Who's buried in Grant's tomb?
type=direct
template=/gift/template/select_template.pl
answer1=Grant
answer2=no one
answer3=Napoleon
answer4=Churchill
answer5=Mother Teresa
right_answer=Grant
