title=rekenen-4.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H5
subject=arithmetic
notion=rekenen-4
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H5/arithmetic/rekenen-4.nl
