title=scheikunde-1.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=chemistry
notion=scheikunde-1
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/chemistry/scheikunde-1.nl
