title=complex-1.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H5
subject=algebra
notion=complex-1
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H5/algebra/complex-1.nl
