# Generated by Django 2.0.4 on 2018-11-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('sourcedid', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
