# Generated by Django 2.0.4 on 2018-12-01 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityoutcome',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playexo.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activityoutcome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activityoutcome',
            unique_together={('url', 'sourcedid')},
        ),
    ]
