title=logica-1.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=logic
notion=logica-1
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/logic/logica-1.nl
