title=oefmoneymarket.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=U3
subject=economics
notion=moneymarket
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U3/economics/oefmoneymarket.fr
