title=domein_en_bereik.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=analysis
notion=domein_en_bereik
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/analysis/domein_en_bereik.nl
