title=OEFevacollege2005.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=analysis
notion=OEFevacollege2005
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/analysis/OEFevacollege2005.fr
