title=equationSnde.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=algebra
notion=equationSnde
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/algebra/equationSnde.fr
