title=chgtRepereR2.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=U2
subject=geometry
notion=chgtRepereR2
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U2/geometry/chgtRepereR2.fr
