title=docpavage.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=U2
subject=geometry
notion=docpavage
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U2/geometry/docpavage.fr
