title=oefsequence.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H5
subject=algo
notion=sequence
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H5/algo/oefsequence.fr
