title=H6~analysis~oeftablevar.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=devel
subject=kobylansDev
notion=H6~analysis~tablevar
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=devel/kobylansDev/H6~analysis~oeftablevar.fr
