title=evolmeth.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=biology
notion=evolmeth
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/biology/evolmeth.fr
