title=coinc_eqdif.en
type=wims
extends=plbank:/demo/wims/template.pl
level=U1
subject=analysis
notion=coinc_eqdif
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U1/analysis/coinc_eqdif.en
