# Generated by Django 2.1.2 on 2018-10-04 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('consumer', models.CharField(blank=True, choices=[('moodle', 'moodle')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=20)),
                ('student', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ManyToManyField(blank=True, related_name='teaches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('consumer', 'consumer_id')},
        ),
    ]
