title=function.es
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=analysis
notion=function
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/analysis/function.es
