title=procentrekenen.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=E6
subject=number
notion=procentrekenen
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=E6/number/procentrekenen.nl
