title=oefgeocomplex.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H6
subject=algebra
notion=geocomplex
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H6/algebra/oefgeocomplex.fr
