title=H6~set~graphset.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=devel
subject=ddoyenDev
notion=H6~set~graphset
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=devel/ddoyenDev/H6~set~graphset.fr
