title=K1~matrix~calculmat.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=devel
subject=ddoyenDev
notion=K1~matrix~calculmat
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=devel/ddoyenDev/K1~matrix~calculmat.fr
