title=K1~set~relations.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=devel
subject=ddoyenDev
notion=K1~set~relations
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=devel/ddoyenDev/K1~set~relations.fr
