# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gitload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.CharField(default=0, max_length=30)),
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pltp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitload.PLTP')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitload.Strategy')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=50000)),
                ('seed', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('ST', 'Commencé'), ('FA', 'Echoué'), ('SU', 'Réussi')], default='ST', max_length=2)),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gitload.PL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
