# Generated by Django 2.0.4 on 2018-05-03 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('open', models.BooleanField(default=True)),
                ('pltp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PLTP')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pltp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PLTP')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=50000)),
                ('seed', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('grade', models.IntegerField()),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
