# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='strategy',
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.CharField(default=0, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
