# Generated by Django 2.1.1 on 2018-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0002_auto_20180816_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='outcome_url',
            field=models.CharField(default='toto', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='sourcedid',
            field=models.CharField(default='titi', max_length=200),
            preserve_default=False,
        ),
    ]
