# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0003_auto_20171130_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
