# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0004_activitytest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
