# Generated by Django 2.1 on 2018-09-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import time


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playexo', '0004_auto_20180905_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sandbox_url', models.CharField(max_length=300, null=True)),
                ('envid', models.UUIDField(null=True)),
                ('activity_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playexo.SessionActivity')),
                ('pl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.PL')),
            ],
        ),
        migrations.RemoveField(
            model_name='activitytest',
            name='pltp',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
        migrations.AddField(
            model_name='answer',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playexo.Activity'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answers',
            field=jsonfield.fields.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='outcome_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sourcedid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='seed',
            field=models.CharField(default=time.time, max_length=100),
        ),
        migrations.DeleteModel(
            name='ActivityTest',
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playexo.Activity'),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='current_pl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loader.PL'),
        ),
        migrations.AddField(
            model_name='sessionactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexercise',
            unique_together={('pl', 'activity_session')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionactivity',
            unique_together={('user', 'activity')},
        ),
    ]
