# Generated by Django 2.1 on 2018-09-05 20:22

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0005_auto_20180905_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='context',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
