# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0005_answer_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='open',
        ),
        migrations.AddField(
            model_name='activity',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
