# Generated by Django 2.1 on 2018-09-06 09:22

from django.db import migrations
import enumfields.fields
import playexo.enums


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0006_sessionexercise_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='status',
            field=enumfields.fields.EnumIntegerField(default=0, enum=playexo.enums.EnvStatus),
        ),
    ]
