# Generated by Django 2.1 on 2018-09-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0007_sessionexercise_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionexercise',
            name='sandbox_url',
        ),
    ]
