title=3ptsPlanR3.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H6
subject=geometry
notion=3ptsPlanR3
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H6/geometry/3ptsPlanR3.fr
