title=OEFeqdteplan.cn
type=wims
extends=plbank:/demo/wims/template.pl
level=H6
subject=geometry
notion=OEFeqdteplan
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H6/geometry/OEFeqdteplan.cn
