title=atome.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=U1
subject=chemistry
notion=atome
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U1/chemistry/atome.fr
