title=addfig.cn
type=wims
extends=plbank:/demo/wims/template.pl
level=H1
subject=algebra
notion=addfig
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H1/algebra/addfig.cn
