title=challenge2006.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H1
subject=algebra
notion=challenge2006
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H1/algebra/challenge2006.fr
