title=vergelijkingen-0.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H1
subject=algebra
notion=vergelijkingen-0
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H1/algebra/vergelijkingen-0.nl
