title=circdraw.en
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=elec
notion=circdraw
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/elec/circdraw.en
