TYPE_ERROR = 'type error'
SYNTAX_ERROR = 'syntax error'
UNDEFINED_VARIABLE = 'undefined variable'
VARIABLE_OVERRIDE = 'variable override'
UNRESOLVED_IMPORT = 'unresolved import'
UNRESOLVED_REFERENCE = 'unresolved reference'
CONTRACT_ERROR = 'contract error'
