# Generated by Django 2.0.6 on 2018-06-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='key',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
