title=economie-0.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H2
subject=financialmath
notion=economie-0
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H2/financialmath/economie-0.nl
