title=machten-2.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H3
subject=algebra
notion=machten-2
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H3/algebra/machten-2.nl
