title=oefeval.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H3
subject=algebra
notion=eval
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H3/algebra/oefeval.fr
