title=oefcountries.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H3
subject=geography
notion=countries
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H3/geography/oefcountries.fr
