title=oefduration.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H2
subject=number
notion=duration
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H2/number/oefduration.fr
