# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PL',
            fields=[
                ('json', jsonfield.fields.JSONField()),
                ('name', models.CharField(max_length=100)),
                ('sha1', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('rel_path', models.CharField(max_length=360)),
                ('zipvalue', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PLTP',
            fields=[
                ('json', jsonfield.fields.JSONField()),
                ('name', models.CharField(max_length=50)),
                ('sha1', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('rel_path', models.CharField(max_length=360)),
                ('pl', models.ManyToManyField(to='gitload.PL')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200, null=True)),
                ('version', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('json', jsonfield.fields.JSONField()),
                ('rel_path', models.CharField(max_length=360)),
                ('repository', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gitload.Repository')),
            ],
        ),
        migrations.AddField(
            model_name='pltp',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gitload.Repository'),
        ),
        migrations.AddField(
            model_name='pl',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gitload.Repository'),
        ),
    ]
