# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 15:53
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Repository = apps.get_model("gitload", "Repository")
    db_alias = schema_editor.connection.alias
    Repository.objects.using(db_alias).bulk_create([
        Repository(name="plbank", url="N/A", version = "N/A"),
    ])

def reverse_func(apps, schema_editor):
    Repository = apps.get_model("gitload", "Repository")
    db_alias = schema_editor.connection.alias
    Repository.objects.using(db_alias).filter(name="plbank").delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('gitload', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
