# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playexo', '0002_auto_20171117_1538'),
        ('gitload', '0002_add_repository_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='repository',
        ),
        migrations.DeleteModel(
            name='Strategy',
        ),
    ]
