title=vervoort-3.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H3
subject=physics
notion=vervoort-3
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H3/physics/vervoort-3.nl
