title=ray3d.es
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=geometry
notion=ray3d
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/geometry/ray3d.es
