title=vision4d.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=geometry
notion=vision4d
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/geometry/vision4d.fr
