title=wimsdoc.en
type=wims
extends=plbank:/demo/wims/template.pl
level=help
subject=wimsdoc.en
notion=
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=help/wimsdoc.en/
