# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('playexo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=20)),
                ('activity', models.ManyToManyField(to='playexo.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='PLUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('activity', models.ManyToManyField(blank=True, to='playexo.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role', models.CharField(choices=[('AD', 'Administrateur'), ('IN', 'Professeur'), ('CD', 'Concepteur'), ('LE', 'Élève'), ('OB', 'Observeur')], default='LE', max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='pluser',
            name='role',
            field=models.ManyToManyField(blank=True, to='classmanagement.Role'),
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
