# Generated by Django 2.1 on 2018-08-16 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='consumer',
            field=models.CharField(blank=True, choices=[('moodle', 'moodle')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='consumer_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('consumer_id', 'consumer_id')},
        ),
    ]
