# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-31 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0002_add_role_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluser',
            name='color_blindness',
            field=models.CharField(choices=[('PR', 'Protanopia'), ('DE', 'Deuteranopia'), ('TR', 'Tritanopia'), ('NO', 'NONE')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('AD', 'Administrator'), ('IN', 'Teacher'), ('CD', 'Conceptor'), ('LE', 'Student'), ('OB', 'Observeur')], default='LE', max_length=2, primary_key=True, serialize=False),
        ),
    ]
