# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-02 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmanagement', '0003_auto_20171031_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluser',
            name='color_blindness',
            field=models.CharField(choices=[('PR', 'Protanope'), ('DE', 'Deuteranope'), ('TR', 'Tritanope'), ('NO', 'Aucun')], default='NO', max_length=2),
        ),
    ]
