title=matmult.it
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=linear
notion=matmult
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/linear/matmult.it
