title=popup.ca
type=wims
extends=plbank:/demo/wims/template.pl
level=tool
subject=popup.ca
notion=
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=tool/popup.ca/
