title=vergelijkingen-1.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H3
subject=analysis
notion=vergelijkingen-1
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H3/analysis/vergelijkingen-1.nl
