title=ruimtemeetkunde-1.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H5
subject=geometry
notion=ruimtemeetkunde-1
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H5/geometry/ruimtemeetkunde-1.nl
