title=vecteurs.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H5
subject=geometry
notion=vecteurs
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H5/geometry/vecteurs.fr
