title=economie-5.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=financialmath
notion=economie-5
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/financialmath/economie-5.nl
