title=OEFCalcLimLnExp.en
type=wims
extends=plbank:/demo/wims/template.pl
level=H6
subject=analysis
notion=OEFCalcLimLnExp
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H6/analysis/OEFCalcLimLnExp.en
