title=oefnumber.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=E1
subject=number
notion=number
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=E1/number/oefnumber.fr
