title=oefdescartes.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=optics
notion=descartes
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/optics/oefdescartes.fr
