title=cirkels-1.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=geometry
notion=cirkels-1
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/geometry/cirkels-1.nl
