title=geoAnaSndeSyn.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=geometry
notion=geoAnaSndeSyn
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/geometry/geoAnaSndeSyn.fr
