title=goniografiek-3.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=geometry
notion=goniografiek-3
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/geometry/goniografiek-3.nl
