title=hammcomple.cn
type=wims
extends=plbank:/demo/wims/template.pl
level=U4
subject=coding
notion=hammcomple
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U4/coding/hammcomple.cn
