title=oefpartition.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=U3
subject=algebra
notion=partition
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U3/algebra/oefpartition.fr
