title=docmodtooloef.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=help
subject=developer
notion=docmodtool
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=help/developer/docmodtooloef.fr
