# Generated by Django 2.0.4 on 2018-11-26 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import user_profile.enums
import user_profile.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playexo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_id', models.CharField(blank=True, max_length=200, null=True)),
                ('consumer', models.CharField(blank=True, choices=[('moodle', 'moodle')], max_length=200, null=True)),
                ('student_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('editor_theme', enumfields.fields.EnumIntegerField(default=9, enum=user_profile.enums.EditorTheme)),
                ('role', enumfields.fields.EnumIntegerField(default=4, enum=user_profile.enums.Role)),
                ('color_blindness', enumfields.fields.EnumIntegerField(default=0, enum=user_profile.enums.ColorBlindness)),
                ('confirm', models.BooleanField(default=True)),
                ('rep', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, upload_to=user_profile.utils.avatar_path)),
                ('activity', models.ManyToManyField(blank=True, to='playexo.Activity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('consumer', 'consumer_id')},
        ),
    ]
