title=foncCoordR4.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=U1
subject=geometry
notion=foncCoordR4
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=U1/geometry/foncCoordR4.fr
