title=faq.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=help
subject=teacher
notion=faq
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=help/teacher/faq.fr
