title=oefsport.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=E5
subject=physeduc
notion=sport
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=E5/physeduc/oefsport.fr
