# Generated by Django 2.0.4 on 2018-11-26 16:12

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filebrowser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Indexes',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='PL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', jsonfield.fields.JSONField(default={})),
                ('name', models.CharField(max_length=100)),
                ('rel_path', models.CharField(max_length=360)),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filebrowser.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='PLTP',
            fields=[
                ('sha1', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('json', jsonfield.fields.JSONField(default={})),
                ('name', models.CharField(max_length=50)),
                ('rel_path', models.CharField(max_length=360, null=True)),
                ('directory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filebrowser.Directory')),
                ('pl', models.ManyToManyField(through='loader.Index', to='loader.PL')),
            ],
        ),
        migrations.AddField(
            model_name='index',
            name='pl',
             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PL'),
        ),
        migrations.AddField(
            model_name='index',
            name='pltp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loader.PLTP'),
        ),
        migrations.AlterUniqueTogether(
            name='index',
            unique_together={('pltp', 'index')},
        ),
    ]
