# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=860)),
            ],
        ),
    ]
