# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=860, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=200, help_text='0 - 2147483647, the smallest number have the highest piority)')),
            ],
        ),
    ]
