# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandbox',
            name='priority',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sandbox',
            name='url',
            field=models.CharField(max_length=860, primary_key=True, serialize=False),
        ),
    ]
