# Generated by Django 2.1 on 2018-09-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sandbox',
        ),
    ]
