# Generated by Django 2.0.4 on 2018-04-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='url',
            field=models.CharField(help_text='http://127.0.0.1:8000/sandbox/?action=execute', max_length=860, primary_key=True, serialize=False),
        ),
    ]
