# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0002_auto_20171110_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandbox',
            name='priority',
            field=models.IntegerField(default=200, help_text='0 - 2147483647, the smallest number have the highest piority)'),
        ),
    ]
