title=Fill-the-blank
text1=Two plus
text2=equals four.
type=direct
template=/gift/template/fill_the_blank_template.pl
answer1=two
answer2=2
feedback1=With alphabetic characters, well done!
feedback2=With numeric characters, not bad!
