title=stat-0.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H2
subject=stat
notion=stat-0
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H2/stat/stat-0.nl
