# Generated by Django 2.1 on 2018-08-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebrowser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
