title=oefgraduation.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=E3
subject=number
notion=graduation
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=E3/number/oefgraduation.fr
