title=pendule1.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=physics
notion=pendule1
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/physics/pendule1.fr
