title=fracrevis2.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=number
notion=fracrevis2
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/number/fracrevis2.fr
