title=stat-2.nl
type=wims
extends=plbank:/demo/wims/template.pl
level=H4
subject=stat
notion=stat-2
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H4/stat/stat-2.nl
