title=OEFprogConstr.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=E6
subject=geometry
notion=OEFprogConstr
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=E6/geometry/OEFprogConstr.fr
