title=oefproba.fr
type=wims
extends=plbank:/demo/wims/template.pl
level=H6
subject=probability
notion=proba
ident=pltest
quser=qcoumes
passwd=toto
course=8109815
url=https://wims.u-pem.fr/wims.cgi?lang=fr&cmd=new&module=H6/probability/oefproba.fr
